project_id = "mbloebaovvvgfwxsdzgo"

[functions.voice-assistant]
verify_jwt = true

[functions.check-test-reminders]
verify_jwt = false

[functions.create-injury-notifications]
verify_jwt = false

[functions.predict-injuries]
verify_jwt = true

[functions.push-notifications]
verify_jwt = false

[functions.check-awcr-alerts]
verify_jwt = false

[functions.send-athlete-invitation]
verify_jwt = false

[functions.notify-athletes]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false
