# services supabase self hosted
# include:
#   - ${PWD}/devops/supabase/supabase/docker-compose.yml

services:
  frontend:
    image: localhost/oven/bun
    build:
      context: .
      dockerfile: devops/bun/Dockerfile

    working_dir: /app
    env_file:
      - .env
      - ".env.${NODE_ENV}"

    tty: true
    stdin_open: true
    init: true

    userns_mode: "keep-id"
    user: "${UID}:${GID}"

    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "${PORT}:${PORT}"

    volumes:
      - ${PWD}:/app:Z
      - ${HOME}/.cache/bun:/home/bun/.cache/bun:Z
      - ${HOME}/.bun:/home/bun/.bun:Z
      # - ${DOCKER_SOCKET_LOCATION}:/var/run/docker.sock:ro,z
