import type { Config } from "tailwindcss";

export default {
  darkMode: ["class", ":is(.dark, .field-mode)"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        "surface-primary": "hsl(var(--surface-primary))",
        "surface-secondary": "hsl(var(--surface-secondary))",
        "surface-tertiary": "hsl(var(--surface-tertiary))",
        "card-background": "hsl(var(--card-background))",
        "elevated-background": "hsl(var(--elevated-background))",
        "input-background": "hsl(var(--input-background))",
        "modal-background": "hsl(var(--modal-background))",
        "text-primary": "hsl(var(--text-primary))",
        "text-secondary": "hsl(var(--text-secondary))",
        "text-muted": "hsl(var(--text-muted))",
        "text-disabled": "hsl(var(--text-disabled))",
        "text-inverse": "hsl(var(--text-inverse))",
        "text-on-primary": "hsl(var(--text-on-primary))",
        "text-on-success": "hsl(var(--text-on-success))",
        "text-on-danger": "hsl(var(--text-on-danger))",
        "action-primary": "hsl(var(--action-primary))",
        "action-primary-foreground": "hsl(var(--action-primary-foreground))",
        "action-secondary": "hsl(var(--action-secondary))",
        "selected-background": "hsl(var(--selected-background))",
        "selected-foreground": "hsl(var(--selected-foreground))",
        "hover-background": "hsl(var(--hover-background))",
        "focus-ring": "hsl(var(--focus-ring))",
        "disabled-background": "hsl(var(--disabled-background))",
        "border-default": "hsl(var(--border-default))",
        "border-subtle": "hsl(var(--border-subtle))",
        "border-focus": "hsl(var(--border-focus))",
        "danger": "hsl(var(--danger))",
        "info": "hsl(var(--info))",
        "wellness": "hsl(var(--wellness))",
        "surface": "hsl(var(--surface))",
        "surface-elevated": "hsl(var(--surface-elevated))",
        "surface-sunken": "hsl(var(--surface-sunken))",
        "action-primary-hover": "hsl(var(--action-primary-hover))",
        "border-strong": "hsl(var(--border-strong))",

        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        selection: {
          DEFAULT: "hsl(var(--selection))",
          foreground: "hsl(var(--selection-foreground))",
          border: "hsl(var(--selection-border))",
        },
        overlay: "hsl(var(--overlay))",
        notification: { DEFAULT: "hsl(var(--notification))", foreground: "hsl(var(--notification-foreground))" },
        "danger-text": "hsl(var(--danger-text))",
        observation: {
          pocket: "hsl(var(--observation-pocket))",
          split: "hsl(var(--observation-split))",
          "on-foreground": "hsl(var(--observation-on-foreground))",
          no: "hsl(var(--observation-no))",
          "no-foreground": "hsl(var(--observation-no-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        "bowling-canvas": "hsl(var(--bowling-canvas))",
        "bowling-accent": "hsl(var(--bowling-accent))",
        "bowling-ink": "hsl(var(--bowling-ink))",
        "bowling-ink-2": "hsl(var(--bowling-ink-2))",
        "bowling-field": "hsl(var(--bowling-field))",
        "bowling-success": "hsl(var(--bowling-success))",
        "bowling-coral": "hsl(var(--bowling-coral))",
        "bowling-tactical": "hsl(var(--bowling-tactical))",
        "bowling-technical": "hsl(var(--bowling-technical))",
        "bowling-games": "hsl(var(--bowling-games))",
        "judo-ink": "hsl(var(--judo-ink))",
        "judo-canvas": "hsl(var(--judo-canvas))",
        "judo-soft": "hsl(var(--judo-soft))",
        "judo-technique": "hsl(var(--judo-technique))",
        "judo-tactic": "hsl(var(--judo-tactic))",
        "judo-randori": "hsl(var(--judo-randori))",
        "judo-physical": "hsl(var(--judo-physical))",
        "judo-mental": "hsl(var(--judo-mental))",
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        status: {
          optimal: "hsl(var(--status-optimal))",
          attention: "hsl(var(--status-attention))",
          critical: "hsl(var(--status-critical))",
        },
        risk: {
          low: "hsl(var(--risk-low))",
          medium: "hsl(var(--risk-medium))",
          high: "hsl(var(--risk-high))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        training: {
          collectif: "hsl(var(--training-collectif))",
          technique: "hsl(var(--training-technique))",
          physique: "hsl(var(--training-physique))",
          musculation: "hsl(var(--training-musculation))",
          repos: "hsl(var(--training-repos))",
          test: "hsl(var(--training-test))",
        },
        nav: {
          overview: "hsl(var(--nav-overview))",
          admin: "hsl(var(--nav-admin))",
          effectif: "hsl(var(--nav-effectif))",
          planification: "hsl(var(--nav-planification))",
          programmation: "hsl(var(--nav-programmation))",
          performance: "hsl(var(--nav-performance))",
          sante: "hsl(var(--nav-sante))",
          competition: "hsl(var(--nav-competition))",
          gps: "hsl(var(--nav-gps))",
          video: "hsl(var(--nav-video))",
          communication: "hsl(var(--nav-communication))",
          settings: "hsl(var(--nav-settings))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { transform: "translateX(-8px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "pulse-alert": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "pulse-alert": "pulse-alert 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "scale-in": "scale-in 0.2s ease-out",
      },
      backgroundImage: {
        "gradient-hero": "var(--gradient-hero)",
        "gradient-card": "var(--gradient-card)",
        "gradient-performance": "var(--gradient-performance)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
