-- Ajouter les exercices par catégorie

-- ==================== CARDIO/ENDURANCE ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Cardio/Endurance', 'Vélo stationnaire / Stationary Bike', 'Pédalage continu sur vélo fixe pour développer l''endurance cardiovasculaire', 'débutant', true, false),
('Cardio/Endurance', 'Rameur / Rowing Machine', 'Effort complet corps entier sur ergomètre', 'débutant', true, false),
('Cardio/Endurance', 'Ski Erg', 'Simulation de ski de fond pour cardio et haut du corps', 'intermédiaire', true, false),
('Cardio/Endurance', 'Echo Bike / Assault Bike', 'Vélo avec bras pour effort maximal', 'intermédiaire', true, false),
('Cardio/Endurance', 'Course / Run (zone 2)', 'Course à allure modérée en endurance fondamentale', 'débutant', true, false),
('Cardio/Endurance', 'Course / Run (tempo)', 'Course à allure seuil pour améliorer la VMA', 'intermédiaire', true, false),
('Cardio/Endurance', 'Corde à sauter / Jump Rope', 'Saut à la corde pour cardio et coordination', 'débutant', true, false),
('Cardio/Endurance', 'Natation / Swimming', 'Nage libre ou autre style pour endurance', 'débutant', true, false),
('Cardio/Endurance', 'Marche inclinée / Incline Walking', 'Marche sur tapis en pente pour cardio bas impact', 'débutant', true, false),
('Cardio/Endurance', 'Vélo elliptique / Elliptical', 'Mouvement elliptique pour cardio sans impact', 'débutant', true, false),
('Cardio/Endurance', 'Stepper / Stair Climber', 'Simulation de montée d''escaliers', 'intermédiaire', true, false),
('Cardio/Endurance', 'Fartlek', 'Course avec variations d''allure spontanées', 'intermédiaire', true, false),
('Cardio/Endurance', 'Intervalles aérobie', 'Alternance effort/récupération en zone aérobie', 'intermédiaire', true, false),
('Cardio/Endurance', 'Course longue / Long Run', 'Sortie longue pour développer l''endurance', 'intermédiaire', true, false),
('Cardio/Endurance', 'Aquajogging', 'Course dans l''eau pour cardio sans impact', 'débutant', true, false)
ON CONFLICT DO NOTHING;

-- ==================== VITESSE/PLYOMÉTRIE ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Vitesse/Plyométrie', 'Box Jumps', 'Sauts sur box pour développer la puissance', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Broad Jumps / Sauts en longueur', 'Sauts horizontaux pour la puissance', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Depth Jumps', 'Sauts en contrebas puis rebond immédiat', 'avancé', true, false),
('Vitesse/Plyométrie', 'Tuck Jumps', 'Sauts groupés avec genoux vers poitrine', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Squat Jumps', 'Sauts depuis position squat', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Split Jumps / Jumping Lunges', 'Fentes sautées alternées', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Bounds / Foulées bondissantes', 'Bonds alternés pour puissance de course', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Skater Jumps', 'Sauts latéraux d''un pied à l''autre', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Hurdle Hops', 'Sauts par-dessus haies successives', 'avancé', true, false),
('Vitesse/Plyométrie', 'Single Leg Hops', 'Sauts sur une jambe', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Lateral Box Jumps', 'Sauts latéraux sur box', 'avancé', true, false),
('Vitesse/Plyométrie', 'Sprints 20m', 'Sprints courts pour explosivité', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Sprints 40m', 'Sprints moyens pour vitesse maximale', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Sprints 60m', 'Sprints pour maintien de vitesse', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Sprints en côte / Hill Sprints', 'Sprints en montée pour puissance', 'avancé', true, false),
('Vitesse/Plyométrie', 'Sprints avec résistance (sled/parachute)', 'Sprints avec charge pour force-vitesse', 'avancé', true, false),
('Vitesse/Plyométrie', 'Accélérations progressives', 'Montée en vitesse progressive', 'débutant', true, false),
('Vitesse/Plyométrie', 'Flying Sprints', 'Sprints lancés à vitesse maximale', 'avancé', true, false),
('Vitesse/Plyométrie', 'Medicine Ball Throws', 'Lancers de medecine ball explosifs', 'intermédiaire', true, false),
('Vitesse/Plyométrie', 'Clap Push-ups', 'Pompes explosives avec claquement', 'avancé', true, false),
('Vitesse/Plyométrie', 'Burpee Broad Jump', 'Burpees avec saut en longueur', 'avancé', true, false),
('Vitesse/Plyométrie', 'Reactive Agility Drills', 'Exercices de réactivité et changement de direction', 'intermédiaire', true, false)
ON CONFLICT DO NOTHING;

-- ==================== HALTÉROPHILIE ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Haltérophilie', 'Arraché / Snatch', 'Mouvement olympique complet barre du sol à bras tendus', 'avancé', true, false),
('Haltérophilie', 'Épaulé-jeté / Clean & Jerk', 'Mouvement olympique en deux temps', 'avancé', true, false),
('Haltérophilie', 'Power Snatch', 'Arraché sans squat complet', 'intermédiaire', true, false),
('Haltérophilie', 'Power Clean', 'Épaulé sans squat complet', 'intermédiaire', true, false),
('Haltérophilie', 'Hang Snatch', 'Arraché depuis position suspendue', 'intermédiaire', true, false),
('Haltérophilie', 'Hang Clean', 'Épaulé depuis position suspendue', 'intermédiaire', true, false),
('Haltérophilie', 'Snatch Pull', 'Tirage d''arraché pour technique', 'intermédiaire', true, false),
('Haltérophilie', 'Clean Pull', 'Tirage d''épaulé pour technique', 'intermédiaire', true, false),
('Haltérophilie', 'Snatch Balance', 'Équilibre d''arraché pour mobilité et timing', 'avancé', true, false),
('Haltérophilie', 'Overhead Squat', 'Squat avec barre au-dessus de la tête', 'avancé', true, false),
('Haltérophilie', 'Front Squat', 'Squat avec barre en position rack', 'intermédiaire', true, false),
('Haltérophilie', 'Split Jerk', 'Jeté en fente', 'avancé', true, false),
('Haltérophilie', 'Push Jerk', 'Jeté avec réception en squat partiel', 'intermédiaire', true, false),
('Haltérophilie', 'Push Press', 'Développé poussé avec impulsion des jambes', 'intermédiaire', true, false),
('Haltérophilie', 'Snatch Deadlift', 'Soulevé de terre prise arraché', 'intermédiaire', true, false),
('Haltérophilie', 'Clean Deadlift', 'Soulevé de terre prise épaulé', 'intermédiaire', true, false),
('Haltérophilie', 'Muscle Snatch', 'Arraché bras tendus sans squat', 'intermédiaire', true, false),
('Haltérophilie', 'Muscle Clean', 'Épaulé sans squat', 'intermédiaire', true, false),
('Haltérophilie', 'Snatch Grip RDL', 'Romanian Deadlift prise arraché', 'intermédiaire', true, false),
('Haltérophilie', 'High Pull', 'Tirage haut pour explosivité', 'intermédiaire', true, false),
('Haltérophilie', 'Dumbbell Snatch', 'Arraché haltère une main', 'intermédiaire', true, false),
('Haltérophilie', 'Kettlebell Snatch', 'Arraché kettlebell', 'intermédiaire', true, false),
('Haltérophilie', 'Behind Neck Jerk', 'Jeté derrière la nuque pour technique', 'avancé', true, false),
('Haltérophilie', 'Pause Snatch', 'Arraché avec pause au genou', 'avancé', true, false),
('Haltérophilie', 'Pause Clean', 'Épaulé avec pause au genou', 'avancé', true, false)
ON CONFLICT DO NOTHING;

-- ==================== GAINAGE/CORE ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Gainage/Core', 'Planche / Plank', 'Gainage statique face au sol', 'débutant', true, false),
('Gainage/Core', 'Planche latérale / Side Plank', 'Gainage latéral sur un bras', 'débutant', true, false),
('Gainage/Core', 'Dead Bug', 'Coordination anti-extension du dos', 'débutant', true, false),
('Gainage/Core', 'Bird Dog', 'Extension bras/jambe opposés quadrupédie', 'débutant', true, false),
('Gainage/Core', 'Hollow Hold', 'Position creuse maintenue', 'intermédiaire', true, false),
('Gainage/Core', 'Hollow Rocks', 'Balancement en position creuse', 'intermédiaire', true, false),
('Gainage/Core', 'V-Ups', 'Montée simultanée buste et jambes', 'intermédiaire', true, false),
('Gainage/Core', 'Toes to Bar', 'Pieds à la barre suspendu', 'avancé', true, false),
('Gainage/Core', 'Knees to Elbows', 'Genoux aux coudes suspendu', 'intermédiaire', true, false),
('Gainage/Core', 'L-Sit', 'Maintien en L suspendu ou parallettes', 'avancé', true, false),
('Gainage/Core', 'Ab Wheel Rollout', 'Roulette abdominale', 'intermédiaire', true, false),
('Gainage/Core', 'Pallof Press', 'Presse anti-rotation avec câble', 'intermédiaire', true, false),
('Gainage/Core', 'Suitcase Carry', 'Marche avec poids d''un côté', 'intermédiaire', true, false),
('Gainage/Core', 'Farmers Carry', 'Marche avec poids des deux côtés', 'débutant', true, false),
('Gainage/Core', 'Overhead Carry', 'Marche avec poids au-dessus de la tête', 'intermédiaire', true, false),
('Gainage/Core', 'Turkish Get-Up', 'Relevé turc complet', 'avancé', true, false),
('Gainage/Core', 'Dragon Flag', 'Drapeau du dragon', 'avancé', true, false),
('Gainage/Core', 'GHD Sit-ups', 'Abdos sur appareil GHD', 'avancé', true, false),
('Gainage/Core', 'Hip Raises', 'Relevés de hanches au sol', 'débutant', true, false),
('Gainage/Core', 'Russian Twists', 'Rotations russes', 'intermédiaire', true, false),
('Gainage/Core', 'Mountain Climbers', 'Grimpeur pour cardio et core', 'débutant', true, false),
('Gainage/Core', 'Plank with Shoulder Tap', 'Planche avec toucher d''épaule', 'intermédiaire', true, false),
('Gainage/Core', 'Anti-Rotation Hold', 'Maintien anti-rotation avec câble', 'intermédiaire', true, false),
('Gainage/Core', 'Hanging Leg Raises', 'Relevés de jambes suspendu', 'intermédiaire', true, false),
('Gainage/Core', 'Copenhagen Plank', 'Planche latérale avec adducteurs', 'avancé', true, false)
ON CONFLICT DO NOTHING;

-- ==================== POIDS DE CORPS/CALISTHENICS ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Poids de corps/Calisthenics', 'Pompes / Push-ups', 'Flexions de bras classiques', 'débutant', true, false),
('Poids de corps/Calisthenics', 'Pompes diamant / Diamond Push-ups', 'Pompes mains rapprochées', 'intermédiaire', true, false),
('Poids de corps/Calisthenics', 'Pompes archer / Archer Push-ups', 'Pompes avec extension latérale', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Pompes pike / Pike Push-ups', 'Pompes position pike pour épaules', 'intermédiaire', true, false),
('Poids de corps/Calisthenics', 'Handstand Push-ups', 'Pompes en équilibre', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Tractions / Pull-ups', 'Tractions prise pronation', 'intermédiaire', true, false),
('Poids de corps/Calisthenics', 'Chin-ups', 'Tractions prise supination', 'intermédiaire', true, false),
('Poids de corps/Calisthenics', 'Muscle-ups', 'Traction suivie d''une dips', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Dips', 'Flexions aux barres parallèles', 'intermédiaire', true, false),
('Poids de corps/Calisthenics', 'Ring Dips', 'Dips aux anneaux', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Ring Muscle-ups', 'Muscle-ups aux anneaux', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Pistol Squats', 'Squats sur une jambe', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Squats poids de corps', 'Squats sans charge', 'débutant', true, false),
('Poids de corps/Calisthenics', 'Fentes / Lunges', 'Fentes avant', 'débutant', true, false),
('Poids de corps/Calisthenics', 'Step-ups', 'Montées sur box', 'débutant', true, false),
('Poids de corps/Calisthenics', 'Bulgarian Split Squat', 'Fente pied arrière surélevé', 'intermédiaire', true, false),
('Poids de corps/Calisthenics', 'Inverted Rows', 'Tirages inversés', 'débutant', true, false),
('Poids de corps/Calisthenics', 'Skin the Cat', 'Rotation complète aux anneaux', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Front Lever', 'Levier avant suspendu', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Back Lever', 'Levier arrière suspendu', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Planche (calisthenics)', 'Position planche bras tendus', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Human Flag', 'Drapeau humain', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Handstand / Équilibre', 'Maintien en équilibre sur les mains', 'avancé', true, false),
('Poids de corps/Calisthenics', 'Burpees', 'Mouvement complet cardio', 'intermédiaire', true, false),
('Poids de corps/Calisthenics', 'Strict Pull-ups', 'Tractions strictes sans kipping', 'intermédiaire', true, false)
ON CONFLICT DO NOTHING;

-- ==================== ATHLÉTISME/RUNNING DRILLS ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Athlétisme/Running drills', 'Montées de genoux / High Knees', 'Genoux hauts sur place ou en déplacement', 'débutant', true, false),
('Athlétisme/Running drills', 'Talons-fesses / Butt Kicks', 'Talons aux fesses', 'débutant', true, false),
('Athlétisme/Running drills', 'Skipping / A-Skip', 'Sautillés avec montée de genou', 'débutant', true, false),
('Athlétisme/Running drills', 'B-Skip', 'Sautillés avec extension jambe', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'C-Skip', 'Sautillés avec griffé arrière', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Carioca / Karaoke', 'Déplacements latéraux croisés', 'débutant', true, false),
('Athlétisme/Running drills', 'Pas chassés / Shuffle', 'Déplacements latéraux rapides', 'débutant', true, false),
('Athlétisme/Running drills', 'Foulées bondissantes / Bounds', 'Bonds alternés pour puissance', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Griffés / Pawing', 'Griffé du pied au sol', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Jambes tendues / Straight Leg Run', 'Course jambes tendues', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Accélérations 30m', 'Accélérations progressives courtes', 'débutant', true, false),
('Athlétisme/Running drills', 'Départs debout', 'Départs explosifs position debout', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Départs 3 points', 'Départs explosifs position 3 appuis', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Départs blocks', 'Départs en starting-blocks', 'avancé', true, false),
('Athlétisme/Running drills', 'Haies basses', 'Passage de haies pour mobilité', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Coordination échelle / Ladder Drills', 'Exercices d''agilité sur échelle', 'débutant', true, false),
('Athlétisme/Running drills', 'Shuttle Run / Navette', 'Courses navettes avec changement direction', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'T-Drill', 'Parcours en T pour agilité', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Pro Agility / 5-10-5', 'Test d''agilité standard', 'intermédiaire', true, false),
('Athlétisme/Running drills', 'Ankling', 'Petits pas rapides cheville', 'débutant', true, false),
('Athlétisme/Running drills', 'Marche athlétique', 'Marche technique d''échauffement', 'débutant', true, false),
('Athlétisme/Running drills', 'Foulées / Strides', 'Accélérations progressives 80-100m', 'débutant', true, false)
ON CONFLICT DO NOTHING;

-- ==================== PRÉVENTION/RENFORCEMENT ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Prévention/Renforcement', 'Clamshell', 'Ouverture hanches allongé latéral', 'débutant', true, false),
('Prévention/Renforcement', 'Monster Walks (élastique)', 'Marche latérale avec élastique', 'débutant', true, false),
('Prévention/Renforcement', 'Fire Hydrants', 'Ouverture hanche quadrupédie', 'débutant', true, false),
('Prévention/Renforcement', 'Glute Bridge', 'Pont fessier au sol', 'débutant', true, false),
('Prévention/Renforcement', 'Single Leg Glute Bridge', 'Pont fessier une jambe', 'intermédiaire', true, false),
('Prévention/Renforcement', 'Nordic Hamstring Curl', 'Curl ischio-jambiers nordique', 'avancé', true, false),
('Prévention/Renforcement', 'Reverse Nordic', 'Extension quadriceps nordique', 'intermédiaire', true, false),
('Prévention/Renforcement', 'Tibialis Raises', 'Relevés tibial antérieur', 'débutant', true, false),
('Prévention/Renforcement', 'Calf Raises (2 jambes)', 'Relevés de mollets', 'débutant', true, false),
('Prévention/Renforcement', 'Single Leg Calf Raise', 'Relevés de mollet une jambe', 'intermédiaire', true, false),
('Prévention/Renforcement', 'Face Pulls', 'Tirages visage pour coiffe des rotateurs', 'débutant', true, false),
('Prévention/Renforcement', 'Band Pull-Aparts', 'Écartés élastique pour dos', 'débutant', true, false),
('Prévention/Renforcement', 'External Rotation (élastique)', 'Rotation externe épaule', 'débutant', true, false),
('Prévention/Renforcement', 'Internal Rotation (élastique)', 'Rotation interne épaule', 'débutant', true, false),
('Prévention/Renforcement', 'YTWL Raises', 'Renforcement scapulaire en Y, T, W, L', 'débutant', true, false),
('Prévention/Renforcement', 'Scapular Push-ups', 'Protraction/rétraction scapulaire', 'débutant', true, false),
('Prévention/Renforcement', 'Prone I-Y-T', 'Renforcement dos allongé face au sol', 'débutant', true, false),
('Prévention/Renforcement', 'Wall Slides', 'Glissement bras contre mur', 'débutant', true, false),
('Prévention/Renforcement', 'Terminal Knee Extension (TKE)', 'Extension terminale genou', 'débutant', true, false),
('Prévention/Renforcement', 'VMO Activation', 'Activation vaste médial oblique', 'débutant', true, false),
('Prévention/Renforcement', 'Hip Flexor March', 'Marche sur place psoas', 'débutant', true, false),
('Prévention/Renforcement', 'Single Leg Balance', 'Équilibre unipodal', 'débutant', true, false),
('Prévention/Renforcement', 'Single Leg RDL', 'Soulevé terre roumain une jambe', 'intermédiaire', true, false),
('Prévention/Renforcement', 'Copenhagen Adductor', 'Renforcement adducteurs latéral', 'avancé', true, false),
('Prévention/Renforcement', 'Banded Hip Flexion', 'Flexion hanche avec élastique', 'débutant', true, false)
ON CONFLICT DO NOTHING;

-- ==================== RESPIRATION ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Respiration', 'Respiration diaphragmatique', 'Respiration profonde par le ventre', 'débutant', true, false),
('Respiration', 'Box Breathing (4-4-4-4)', 'Respiration carrée : inspire, retient, expire, retient', 'débutant', true, false),
('Respiration', 'Cohérence cardiaque (5-5)', 'Respiration 5s inspire / 5s expire', 'débutant', true, false),
('Respiration', 'Respiration Wim Hof', 'Hyperventilation contrôlée puis rétention', 'intermédiaire', true, false),
('Respiration', '4-7-8 Breathing', 'Inspire 4s, retient 7s, expire 8s', 'débutant', true, false),
('Respiration', 'Respiration costale', 'Expansion latérale des côtes', 'débutant', true, false),
('Respiration', 'Respiration nasale alternée', 'Alternance narine gauche/droite', 'débutant', true, false),
('Respiration', 'Apnée statique', 'Rétention de souffle sans mouvement', 'intermédiaire', true, false),
('Respiration', 'Apnée dynamique', 'Rétention de souffle avec mouvement', 'avancé', true, false),
('Respiration', 'Respiration 90/90', 'Respiration en position 90/90 hanches', 'débutant', true, false),
('Respiration', 'Crocodile Breathing', 'Respiration allongé sur le ventre', 'débutant', true, false),
('Respiration', 'Respiration avec résistance', 'Respiration avec outil de restriction', 'intermédiaire', true, false),
('Respiration', 'Power Breathing', 'Respiration explosive pré-effort', 'intermédiaire', true, false),
('Respiration', 'Recovery Breathing', 'Respiration de récupération post-effort', 'débutant', true, false),
('Respiration', 'Buteyko Method', 'Réduction du volume respiratoire', 'intermédiaire', true, false)
ON CONFLICT DO NOTHING;

-- ==================== RÉATHLÉTISATION ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Réathlétisation', 'Marche contrôlée', 'Marche avec focus technique', 'débutant', true, false),
('Réathlétisation', 'Marche arrière', 'Marche en arrière pour proprioception', 'débutant', true, false),
('Réathlétisation', 'Marche latérale', 'Marche de côté avec contrôle', 'débutant', true, false),
('Réathlétisation', 'Jogging léger', 'Course à très basse intensité', 'débutant', true, false),
('Réathlétisation', 'Course en ligne droite', 'Course contrôlée sans changement direction', 'débutant', true, false),
('Réathlétisation', 'Course avec changements de direction', 'Course avec virages progressifs', 'intermédiaire', true, false),
('Réathlétisation', 'Squats isométriques', 'Maintien en position squat', 'débutant', true, false),
('Réathlétisation', 'Mini squats', 'Squats avec amplitude réduite', 'débutant', true, false),
('Réathlétisation', 'Step-ups bas', 'Montées sur marche basse', 'débutant', true, false),
('Réathlétisation', 'Vélo sans résistance', 'Pédalage léger pour mobilité', 'débutant', true, false),
('Réathlétisation', 'Aquagym', 'Exercices dans l''eau', 'débutant', true, false),
('Réathlétisation', 'Presse jambes légère', 'Presse avec charge minimale', 'débutant', true, false),
('Réathlétisation', 'Isométrie genou', 'Contractions isométriques quadriceps', 'débutant', true, false),
('Réathlétisation', 'Isométrie épaule', 'Contractions isométriques épaule', 'débutant', true, false),
('Réathlétisation', 'Mobilité articulaire passive', 'Mouvements assistés', 'débutant', true, false),
('Réathlétisation', 'Proprioception instable', 'Exercices sur surface instable', 'intermédiaire', true, false),
('Réathlétisation', 'Réceptions contrôlées', 'Atterrissages progressifs', 'intermédiaire', true, false),
('Réathlétisation', 'Accélérations légères', 'Accélérations à intensité réduite', 'intermédiaire', true, false),
('Réathlétisation', 'Changements direction progressifs', 'Virages de plus en plus serrés', 'intermédiaire', true, false),
('Réathlétisation', 'Retour au geste sportif', 'Pratique technique sport spécifique', 'avancé', true, false)
ON CONFLICT DO NOTHING;

-- ==================== TESTS & ÉVALUATIONS ====================
INSERT INTO exercise_library (station_name, exercise_name, description, difficulty_level, is_default, is_variation) VALUES
('Tests & Évaluations', 'Test VMA (Luc Léger)', 'Test navette 20m pour VMA', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test Cooper', 'Course 12 minutes pour VO2max', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test demi-Cooper', 'Course 6 minutes pour VMA', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test VAMEVAL', 'Test VMA sur piste', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test 1RM', 'Test de répétition maximale', 'avancé', true, false),
('Tests & Évaluations', 'Test 3RM', 'Test 3 répétitions maximales', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test 5RM', 'Test 5 répétitions maximales', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test FMS', 'Functional Movement Screen', 'débutant', true, false),
('Tests & Évaluations', 'Test Beep', 'Test navette intermittent', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test Yo-Yo IR1', 'Test intermittent niveau 1', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test Yo-Yo IR2', 'Test intermittent niveau 2', 'avancé', true, false),
('Tests & Évaluations', 'CMJ (Counter Movement Jump)', 'Saut avec contre-mouvement', 'débutant', true, false),
('Tests & Évaluations', 'SJ (Squat Jump)', 'Saut depuis position statique', 'débutant', true, false),
('Tests & Évaluations', 'Drop Jump Test', 'Test de réactivité en saut', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test détente horizontale', 'Saut en longueur sans élan', 'débutant', true, false),
('Tests & Évaluations', 'Sprint 10m', 'Test de vitesse courte', 'débutant', true, false),
('Tests & Évaluations', 'Sprint 20m', 'Test de vitesse', 'débutant', true, false),
('Tests & Évaluations', 'Sprint 40m', 'Test de vitesse maximale', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test Illinois', 'Test d''agilité', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test T', 'Test d''agilité en T', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test Sit & Reach', 'Test de souplesse ischio-jambiers', 'débutant', true, false),
('Tests & Évaluations', 'Test Thomas', 'Test de souplesse psoas', 'débutant', true, false),
('Tests & Évaluations', 'Test planche (max)', 'Temps maximal en planche', 'débutant', true, false),
('Tests & Évaluations', 'Test pompes max', 'Nombre max de pompes', 'débutant', true, false),
('Tests & Évaluations', 'Test tractions max', 'Nombre max de tractions', 'intermédiaire', true, false),
('Tests & Évaluations', 'Test Wingate', 'Test puissance anaérobie vélo', 'avancé', true, false),
('Tests & Évaluations', 'Test Ruffier-Dickson', 'Test de récupération cardiaque', 'débutant', true, false),
('Tests & Évaluations', 'Pesée / Impédancemétrie', 'Mesure composition corporelle', 'débutant', true, false),
('Tests & Évaluations', 'Test mobilité épaule', 'Évaluation amplitude épaule', 'débutant', true, false),
('Tests & Évaluations', 'Test mobilité hanche', 'Évaluation amplitude hanche', 'débutant', true, false)
ON CONFLICT DO NOTHING;