-- 0. Permettre user_id NULL pour exercices système globaux
ALTER TABLE public.exercise_library ALTER COLUMN user_id DROP NOT NULL;

-- 1. Ajouter colonnes manquantes
ALTER TABLE public.exercise_library
  ADD COLUMN IF NOT EXISTS station_name TEXT,
  ADD COLUMN IF NOT EXISTS video_url TEXT,
  ADD COLUMN IF NOT EXISTS tips TEXT,
  ADD COLUMN IF NOT EXISTS general_description TEXT,
  ADD COLUMN IF NOT EXISTS positioning_criteria JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS execution_criteria JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS safety_prevention JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS joint_movements TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS exercise_type TEXT;

CREATE INDEX IF NOT EXISTS exercise_library_station_name_idx ON public.exercise_library(station_name);

-- 2. Import des exercices système
WITH src(station_name, name, description, difficulty, tips) AS (VALUES
  ('Ski Erg', 'Technique de base Ski Erg', 'Position assise, dos droit, mouvement fluide des bras en coordination avec les jambes. Focus sur la puissance explosive.', 'débutant', 'Gardez le dos droit et utilisez tout votre corps, pas seulement les bras.'),
  ('Ski Erg', 'Ski Erg intervalle court', 'Sprints de 30 secondes avec 30 secondes de repos. Développe la puissance anaérobie.', 'intermédiaire', 'Maintenez une cadence élevée pendant les sprints, récupérez activement.'),
  ('Sled Push', 'Sled Push technique', 'Mains sur les poignées hautes, corps incliné à 45°, poussée explosive avec les jambes.', 'débutant', 'Gardez le corps bas et stable, poussez avec les jambes pas avec les bras.'),
  ('Sled Push', 'Sled Push progressif', 'Augmentation progressive du poids sur 5 sets pour développer la force maximale.', 'avancé', 'Commencez léger pour la technique, augmentez progressivement.'),
  ('Sled Pull', 'Sled Pull main sur main', 'Traction alternée, position stable, utilisation du poids du corps.', 'débutant', 'Utilisez votre poids corporel, gardez les hanches basses.'),
  ('Sled Pull', 'Sled Pull rapide', 'Focus sur la vitesse de traction avec charge modérée.', 'intermédiaire', 'Mouvements rapides et courts, maintenez une bonne posture.'),
  ('Burpee Broad Jump', 'Burpee technique', 'Descente contrôlée, poitrine au sol, saut explosif en avant.', 'débutant', 'Atterrissez stable avant de redescendre, pas de pause inutile.'),
  ('Burpee Broad Jump', 'Burpee broad jump haute intensité', 'Enchaînement rapide avec distance maximale sur chaque saut.', 'avancé', 'Trouvez votre rythme, ne sacrifiez pas la distance pour la vitesse.'),
  ('Row', 'Rowing technique', 'Séquence jambes-dos-bras à la traction, inverse au retour. Damper réglé entre 115-125.', 'débutant', 'Gardez le dos droit, tirez le coude vers l''arrière.'),
  ('Row', 'Row intervalle pyramide', 'Intervalles croissants puis décroissants (100m-200m-300m-200m-100m) avec 1min repos.', 'intermédiaire', 'Maintenez la même intensité sur tous les intervalles.'),
  ('Farmers Carry', 'Farmers carry posture', 'Position verticale, épaules en arrière, regard devant, kettlebells/haltères lourds.', 'débutant', 'Gardez le torse droit, ne vous penchez pas sur les côtés.'),
  ('Farmers Carry', 'Farmers carry avec stops', 'Marche avec arrêts isométriques de 5-10 secondes tous les 10 mètres.', 'avancé', 'Les pauses renforcent la stabilité du core.'),
  ('Sandbag Lunges', 'Lunges technique', 'Genou arrière frôle le sol, buste droit, sandbag sur les épaules.', 'débutant', 'Contrôlez la descente, gardez le poids sur le talon avant.'),
  ('Sandbag Lunges', 'Lunges walking tempo', 'Fentes marchées avec tempo contrôlé (3 secondes descente, 1 seconde montée).', 'intermédiaire', 'Le tempo lent développe la force et le contrôle.'),
  ('Wall Balls', 'Wall ball technique', 'Squat complet, lancer explosif, cible à 3m (H) ou 2.7m (F).', 'débutant', 'Descendez en squat complet, utilisez la force des jambes pour lancer.'),
  ('Wall Balls', 'Wall ball endurance', 'Sets de 25-50 reps non-stop pour développer l''endurance musculaire.', 'intermédiaire', 'Trouvez votre rythme, respirez sur chaque rep.'),
  ('Cardio/Endurance', 'Vélo stationnaire / Stationary Bike', 'Pédalage continu sur vélo fixe pour développer l''endurance cardiovasculaire', 'débutant', NULL),
  ('Cardio/Endurance', 'Rameur / Rowing Machine', 'Effort complet corps entier sur ergomètre', 'débutant', NULL),
  ('Cardio/Endurance', 'Ski Erg', 'Simulation de ski de fond pour cardio et haut du corps', 'intermédiaire', NULL),
  ('Cardio/Endurance', 'Echo Bike / Assault Bike', 'Vélo avec bras pour effort maximal', 'intermédiaire', NULL),
  ('Cardio/Endurance', 'Course / Run (zone 2)', 'Course à allure modérée en endurance fondamentale', 'débutant', NULL),
  ('Cardio/Endurance', 'Course / Run (tempo)', 'Course à allure seuil pour améliorer la VMA', 'intermédiaire', NULL),
  ('Cardio/Endurance', 'Corde à sauter / Jump Rope', 'Saut à la corde pour cardio et coordination', 'débutant', NULL),
  ('Cardio/Endurance', 'Natation / Swimming', 'Nage libre ou autre style pour endurance', 'débutant', NULL),
  ('Cardio/Endurance', 'Marche inclinée / Incline Walking', 'Marche sur tapis en pente pour cardio bas impact', 'débutant', NULL),
  ('Cardio/Endurance', 'Vélo elliptique / Elliptical', 'Mouvement elliptique pour cardio sans impact', 'débutant', NULL),
  ('Cardio/Endurance', 'Stepper / Stair Climber', 'Simulation de montée d''escaliers', 'intermédiaire', NULL),
  ('Cardio/Endurance', 'Fartlek', 'Course avec variations d''allure spontanées', 'intermédiaire', NULL),
  ('Cardio/Endurance', 'Intervalles aérobie', 'Alternance effort/récupération en zone aérobie', 'intermédiaire', NULL),
  ('Cardio/Endurance', 'Course longue / Long Run', 'Sortie longue pour développer l''endurance', 'intermédiaire', NULL),
  ('Cardio/Endurance', 'Aquajogging', 'Course dans l''eau pour cardio sans impact', 'débutant', NULL),
  ('Vitesse/Plyométrie', 'Box Jumps', 'Sauts sur box pour développer la puissance', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Broad Jumps / Sauts en longueur', 'Sauts horizontaux pour la puissance', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Depth Jumps', 'Sauts en contrebas puis rebond immédiat', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Tuck Jumps', 'Sauts groupés avec genoux vers poitrine', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Squat Jumps', 'Sauts depuis position squat', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Split Jumps / Jumping Lunges', 'Fentes sautées alternées', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Bounds / Foulées bondissantes', 'Bonds alternés pour puissance de course', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Skater Jumps', 'Sauts latéraux d''un pied à l''autre', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Hurdle Hops', 'Sauts par-dessus haies successives', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Single Leg Hops', 'Sauts sur une jambe', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Lateral Box Jumps', 'Sauts latéraux sur box', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Sprints 20m', 'Sprints courts pour explosivité', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Sprints 40m', 'Sprints moyens pour vitesse maximale', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Sprints 60m', 'Sprints pour maintien de vitesse', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Sprints en côte / Hill Sprints', 'Sprints en montée pour puissance', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Sprints avec résistance (sled/parachute)', 'Sprints avec charge pour force-vitesse', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Accélérations progressives', 'Montée en vitesse progressive', 'débutant', NULL),
  ('Vitesse/Plyométrie', 'Flying Sprints', 'Sprints lancés à vitesse maximale', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Medicine Ball Throws', 'Lancers de medecine ball explosifs', 'intermédiaire', NULL),
  ('Vitesse/Plyométrie', 'Clap Push-ups', 'Pompes explosives avec claquement', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Burpee Broad Jump', 'Burpees avec saut en longueur', 'avancé', NULL),
  ('Vitesse/Plyométrie', 'Reactive Agility Drills', 'Exercices de réactivité et changement de direction', 'intermédiaire', NULL),
  ('Haltérophilie', 'Arraché / Snatch', 'Mouvement olympique complet barre du sol à bras tendus', 'avancé', NULL),
  ('Haltérophilie', 'Épaulé-jeté / Clean & Jerk', 'Mouvement olympique en deux temps', 'avancé', NULL),
  ('Haltérophilie', 'Power Snatch', 'Arraché sans squat complet', 'intermédiaire', NULL),
  ('Haltérophilie', 'Power Clean', 'Épaulé sans squat complet', 'intermédiaire', NULL),
  ('Haltérophilie', 'Hang Snatch', 'Arraché depuis position suspendue', 'intermédiaire', NULL),
  ('Haltérophilie', 'Hang Clean', 'Épaulé depuis position suspendue', 'intermédiaire', NULL),
  ('Haltérophilie', 'Snatch Pull', 'Tirage d''arraché pour technique', 'intermédiaire', NULL),
  ('Haltérophilie', 'Clean Pull', 'Tirage d''épaulé pour technique', 'intermédiaire', NULL),
  ('Haltérophilie', 'Snatch Balance', 'Équilibre d''arraché pour mobilité et timing', 'avancé', NULL),
  ('Haltérophilie', 'Overhead Squat', 'Squat avec barre au-dessus de la tête', 'avancé', NULL),
  ('Haltérophilie', 'Front Squat', 'Squat avec barre en position rack', 'intermédiaire', NULL),
  ('Haltérophilie', 'Split Jerk', 'Jeté en fente', 'avancé', NULL),
  ('Haltérophilie', 'Push Jerk', 'Jeté avec réception en squat partiel', 'intermédiaire', NULL),
  ('Haltérophilie', 'Push Press', 'Développé poussé avec impulsion des jambes', 'intermédiaire', NULL),
  ('Haltérophilie', 'Snatch Deadlift', 'Soulevé de terre prise arraché', 'intermédiaire', NULL),
  ('Haltérophilie', 'Clean Deadlift', 'Soulevé de terre prise épaulé', 'intermédiaire', NULL),
  ('Haltérophilie', 'Muscle Snatch', 'Arraché bras tendus sans squat', 'intermédiaire', NULL),
  ('Haltérophilie', 'Muscle Clean', 'Épaulé sans squat', 'intermédiaire', NULL),
  ('Haltérophilie', 'Snatch Grip RDL', 'Romanian Deadlift prise arraché', 'intermédiaire', NULL),
  ('Haltérophilie', 'High Pull', 'Tirage haut pour explosivité', 'intermédiaire', NULL),
  ('Haltérophilie', 'Dumbbell Snatch', 'Arraché haltère une main', 'intermédiaire', NULL),
  ('Haltérophilie', 'Kettlebell Snatch', 'Arraché kettlebell', 'intermédiaire', NULL),
  ('Haltérophilie', 'Behind Neck Jerk', 'Jeté derrière la nuque pour technique', 'avancé', NULL),
  ('Haltérophilie', 'Pause Snatch', 'Arraché avec pause au genou', 'avancé', NULL),
  ('Haltérophilie', 'Pause Clean', 'Épaulé avec pause au genou', 'avancé', NULL),
  ('Gainage/Core', 'Planche / Plank', 'Gainage statique face au sol', 'débutant', NULL),
  ('Gainage/Core', 'Planche latérale / Side Plank', 'Gainage latéral sur un bras', 'débutant', NULL),
  ('Gainage/Core', 'Dead Bug', 'Coordination anti-extension du dos', 'débutant', NULL),
  ('Gainage/Core', 'Bird Dog', 'Extension bras/jambe opposés quadrupédie', 'débutant', NULL),
  ('Gainage/Core', 'Hollow Hold', 'Position creuse maintenue', 'intermédiaire', NULL),
  ('Gainage/Core', 'Hollow Rocks', 'Balancement en position creuse', 'intermédiaire', NULL),
  ('Gainage/Core', 'V-Ups', 'Montée simultanée buste et jambes', 'intermédiaire', NULL),
  ('Gainage/Core', 'Toes to Bar', 'Pieds à la barre suspendu', 'avancé', NULL),
  ('Gainage/Core', 'Knees to Elbows', 'Genoux aux coudes suspendu', 'intermédiaire', NULL),
  ('Gainage/Core', 'L-Sit', 'Maintien en L suspendu ou parallettes', 'avancé', NULL),
  ('Gainage/Core', 'Ab Wheel Rollout', 'Roulette abdominale', 'intermédiaire', NULL),
  ('Gainage/Core', 'Pallof Press', 'Presse anti-rotation avec câble', 'intermédiaire', NULL),
  ('Gainage/Core', 'Suitcase Carry', 'Marche avec poids d''un côté', 'intermédiaire', NULL),
  ('Gainage/Core', 'Farmers Carry', 'Marche avec poids des deux côtés', 'débutant', NULL),
  ('Gainage/Core', 'Overhead Carry', 'Marche avec poids au-dessus de la tête', 'intermédiaire', NULL),
  ('Gainage/Core', 'Turkish Get-Up', 'Relevé turc complet', 'avancé', NULL),
  ('Gainage/Core', 'Dragon Flag', 'Drapeau du dragon', 'avancé', NULL),
  ('Gainage/Core', 'GHD Sit-ups', 'Abdos sur appareil GHD', 'avancé', NULL),
  ('Gainage/Core', 'Hip Raises', 'Relevés de hanches au sol', 'débutant', NULL),
  ('Gainage/Core', 'Russian Twists', 'Rotations russes', 'intermédiaire', NULL),
  ('Gainage/Core', 'Mountain Climbers', 'Grimpeur pour cardio et core', 'débutant', NULL),
  ('Gainage/Core', 'Plank with Shoulder Tap', 'Planche avec toucher d''épaule', 'intermédiaire', NULL),
  ('Gainage/Core', 'Anti-Rotation Hold', 'Maintien anti-rotation avec câble', 'intermédiaire', NULL),
  ('Gainage/Core', 'Hanging Leg Raises', 'Relevés de jambes suspendu', 'intermédiaire', NULL),
  ('Gainage/Core', 'Copenhagen Plank', 'Planche latérale avec adducteurs', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Pompes / Push-ups', 'Flexions de bras classiques', 'débutant', NULL),
  ('Poids de corps/Calisthenics', 'Pompes diamant / Diamond Push-ups', 'Pompes mains rapprochées', 'intermédiaire', NULL),
  ('Poids de corps/Calisthenics', 'Pompes archer / Archer Push-ups', 'Pompes avec extension latérale', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Pompes pike / Pike Push-ups', 'Pompes position pike pour épaules', 'intermédiaire', NULL),
  ('Poids de corps/Calisthenics', 'Handstand Push-ups', 'Pompes en équilibre', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Tractions / Pull-ups', 'Tractions prise pronation', 'intermédiaire', NULL),
  ('Poids de corps/Calisthenics', 'Chin-ups', 'Tractions prise supination', 'intermédiaire', NULL),
  ('Poids de corps/Calisthenics', 'Muscle-ups', 'Traction suivie d''une dips', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Dips', 'Flexions aux barres parallèles', 'intermédiaire', NULL),
  ('Poids de corps/Calisthenics', 'Ring Dips', 'Dips aux anneaux', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Ring Muscle-ups', 'Muscle-ups aux anneaux', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Pistol Squats', 'Squats sur une jambe', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Squats poids de corps', 'Squats sans charge', 'débutant', NULL),
  ('Poids de corps/Calisthenics', 'Fentes / Lunges', 'Fentes avant', 'débutant', NULL),
  ('Poids de corps/Calisthenics', 'Step-ups', 'Montées sur box', 'débutant', NULL),
  ('Poids de corps/Calisthenics', 'Bulgarian Split Squat', 'Fente pied arrière surélevé', 'intermédiaire', NULL),
  ('Poids de corps/Calisthenics', 'Inverted Rows', 'Tirages inversés', 'débutant', NULL),
  ('Poids de corps/Calisthenics', 'Skin the Cat', 'Rotation complète aux anneaux', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Front Lever', 'Levier avant suspendu', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Back Lever', 'Levier arrière suspendu', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Planche (calisthenics)', 'Position planche bras tendus', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Human Flag', 'Drapeau humain', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Handstand / Équilibre', 'Maintien en équilibre sur les mains', 'avancé', NULL),
  ('Poids de corps/Calisthenics', 'Burpees', 'Mouvement complet cardio', 'intermédiaire', NULL),
  ('Poids de corps/Calisthenics', 'Strict Pull-ups', 'Tractions strictes sans kipping', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Montées de genoux / High Knees', 'Genoux hauts sur place ou en déplacement', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Talons-fesses / Butt Kicks', 'Talons aux fesses', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Skipping / A-Skip', 'Sautillés avec montée de genou', 'débutant', NULL),
  ('Athlétisme/Running drills', 'B-Skip', 'Sautillés avec extension jambe', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'C-Skip', 'Sautillés avec griffé arrière', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Carioca / Karaoke', 'Déplacements latéraux croisés', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Pas chassés / Shuffle', 'Déplacements latéraux rapides', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Foulées bondissantes / Bounds', 'Bonds alternés pour puissance', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Griffés / Pawing', 'Griffé du pied au sol', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Jambes tendues / Straight Leg Run', 'Course jambes tendues', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Accélérations 30m', 'Accélérations progressives courtes', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Départs debout', 'Départs explosifs position debout', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Départs 3 points', 'Départs explosifs position 3 appuis', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Départs blocks', 'Départs en starting-blocks', 'avancé', NULL),
  ('Athlétisme/Running drills', 'Haies basses', 'Passage de haies pour mobilité', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Coordination échelle / Ladder Drills', 'Exercices d''agilité sur échelle', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Shuttle Run / Navette', 'Courses navettes avec changement direction', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'T-Drill', 'Parcours en T pour agilité', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Pro Agility / 5-10-5', 'Test d''agilité standard', 'intermédiaire', NULL),
  ('Athlétisme/Running drills', 'Ankling', 'Petits pas rapides cheville', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Marche athlétique', 'Marche technique d''échauffement', 'débutant', NULL),
  ('Athlétisme/Running drills', 'Foulées / Strides', 'Accélérations progressives 80-100m', 'débutant', NULL),
  ('Prévention/Renforcement', 'Clamshell', 'Ouverture hanches allongé latéral', 'débutant', NULL),
  ('Prévention/Renforcement', 'Monster Walks (élastique)', 'Marche latérale avec élastique', 'débutant', NULL),
  ('Prévention/Renforcement', 'Fire Hydrants', 'Ouverture hanche quadrupédie', 'débutant', NULL),
  ('Prévention/Renforcement', 'Glute Bridge', 'Pont fessier au sol', 'débutant', NULL),
  ('Prévention/Renforcement', 'Single Leg Glute Bridge', 'Pont fessier une jambe', 'intermédiaire', NULL),
  ('Prévention/Renforcement', 'Nordic Hamstring Curl', 'Curl ischio-jambiers nordique', 'avancé', NULL),
  ('Prévention/Renforcement', 'Reverse Nordic', 'Extension quadriceps nordique', 'intermédiaire', NULL),
  ('Prévention/Renforcement', 'Tibialis Raises', 'Relevés tibial antérieur', 'débutant', NULL),
  ('Prévention/Renforcement', 'Calf Raises (2 jambes)', 'Relevés de mollets', 'débutant', NULL),
  ('Prévention/Renforcement', 'Single Leg Calf Raise', 'Relevés de mollet une jambe', 'intermédiaire', NULL),
  ('Prévention/Renforcement', 'Face Pulls', 'Tirages visage pour coiffe des rotateurs', 'débutant', NULL),
  ('Prévention/Renforcement', 'Band Pull-Aparts', 'Écartés élastique pour dos', 'débutant', NULL),
  ('Prévention/Renforcement', 'External Rotation (élastique)', 'Rotation externe épaule', 'débutant', NULL),
  ('Prévention/Renforcement', 'Internal Rotation (élastique)', 'Rotation interne épaule', 'débutant', NULL),
  ('Prévention/Renforcement', 'YTWL Raises', 'Renforcement scapulaire en Y, T, W, L', 'débutant', NULL),
  ('Prévention/Renforcement', 'Scapular Push-ups', 'Protraction/rétraction scapulaire', 'débutant', NULL),
  ('Prévention/Renforcement', 'Prone I-Y-T', 'Renforcement dos allongé face au sol', 'débutant', NULL),
  ('Prévention/Renforcement', 'Wall Slides', 'Glissement bras contre mur', 'débutant', NULL),
  ('Prévention/Renforcement', 'Terminal Knee Extension (TKE)', 'Extension terminale genou', 'débutant', NULL),
  ('Prévention/Renforcement', 'VMO Activation', 'Activation vaste médial oblique', 'débutant', NULL),
  ('Prévention/Renforcement', 'Hip Flexor March', 'Marche sur place psoas', 'débutant', NULL),
  ('Prévention/Renforcement', 'Single Leg Balance', 'Équilibre unipodal', 'débutant', NULL),
  ('Prévention/Renforcement', 'Single Leg RDL', 'Soulevé terre roumain une jambe', 'intermédiaire', NULL),
  ('Prévention/Renforcement', 'Copenhagen Adductor', 'Renforcement adducteurs latéral', 'avancé', NULL),
  ('Prévention/Renforcement', 'Banded Hip Flexion', 'Flexion hanche avec élastique', 'débutant', NULL),
  ('Respiration', 'Respiration diaphragmatique', 'Respiration profonde par le ventre', 'débutant', NULL),
  ('Respiration', 'Box Breathing (4-4-4-4)', 'Respiration carrée : inspire, retient, expire, retient', 'débutant', NULL),
  ('Respiration', 'Cohérence cardiaque (5-5)', 'Respiration 5s inspire / 5s expire', 'débutant', NULL),
  ('Respiration', 'Respiration Wim Hof', 'Hyperventilation contrôlée puis rétention', 'intermédiaire', NULL),
  ('Respiration', '4-7-8 Breathing', 'Inspire 4s, retient 7s, expire 8s', 'débutant', NULL),
  ('Respiration', 'Respiration costale', 'Expansion latérale des côtes', 'débutant', NULL),
  ('Respiration', 'Respiration nasale alternée', 'Alternance narine gauche/droite', 'débutant', NULL),
  ('Respiration', 'Apnée statique', 'Rétention de souffle sans mouvement', 'intermédiaire', NULL),
  ('Respiration', 'Apnée dynamique', 'Rétention de souffle avec mouvement', 'avancé', NULL),
  ('Respiration', 'Respiration 90/90', 'Respiration en position 90/90 hanches', 'débutant', NULL),
  ('Respiration', 'Crocodile Breathing', 'Respiration allongé sur le ventre', 'débutant', NULL),
  ('Respiration', 'Respiration avec résistance', 'Respiration avec outil de restriction', 'intermédiaire', NULL),
  ('Respiration', 'Power Breathing', 'Respiration explosive pré-effort', 'intermédiaire', NULL),
  ('Respiration', 'Recovery Breathing', 'Respiration de récupération post-effort', 'débutant', NULL),
  ('Respiration', 'Buteyko Method', 'Réduction du volume respiratoire', 'intermédiaire', NULL),
  ('Réathlétisation', 'Marche contrôlée', 'Marche avec focus technique', 'débutant', NULL),
  ('Réathlétisation', 'Marche arrière', 'Marche en arrière pour proprioception', 'débutant', NULL),
  ('Réathlétisation', 'Marche latérale', 'Marche de côté avec contrôle', 'débutant', NULL),
  ('Réathlétisation', 'Jogging léger', 'Course à très basse intensité', 'débutant', NULL),
  ('Réathlétisation', 'Course en ligne droite', 'Course contrôlée sans changement direction', 'débutant', NULL),
  ('Réathlétisation', 'Course avec changements de direction', 'Course avec virages progressifs', 'intermédiaire', NULL),
  ('Réathlétisation', 'Squats isométriques', 'Maintien en position squat', 'débutant', NULL),
  ('Réathlétisation', 'Mini squats', 'Squats avec amplitude réduite', 'débutant', NULL),
  ('Réathlétisation', 'Step-ups bas', 'Montées sur marche basse', 'débutant', NULL),
  ('Réathlétisation', 'Vélo sans résistance', 'Pédalage léger pour mobilité', 'débutant', NULL),
  ('Réathlétisation', 'Aquagym', 'Exercices dans l''eau', 'débutant', NULL),
  ('Réathlétisation', 'Presse jambes légère', 'Presse avec charge minimale', 'débutant', NULL),
  ('Réathlétisation', 'Isométrie genou', 'Contractions isométriques quadriceps', 'débutant', NULL),
  ('Réathlétisation', 'Isométrie épaule', 'Contractions isométriques épaule', 'débutant', NULL),
  ('Réathlétisation', 'Mobilité articulaire passive', 'Mouvements assistés', 'débutant', NULL),
  ('Réathlétisation', 'Proprioception instable', 'Exercices sur surface instable', 'intermédiaire', NULL),
  ('Réathlétisation', 'Réceptions contrôlées', 'Atterrissages progressifs', 'intermédiaire', NULL),
  ('Réathlétisation', 'Accélérations légères', 'Accélérations à intensité réduite', 'intermédiaire', NULL),
  ('Réathlétisation', 'Changements direction progressifs', 'Virages de plus en plus serrés', 'intermédiaire', NULL),
  ('Réathlétisation', 'Retour au geste sportif', 'Pratique technique sport spécifique', 'avancé', NULL),
  ('Tests & Évaluations', 'Test VMA (Luc Léger)', 'Test navette 20m pour VMA', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test Cooper', 'Course 12 minutes pour VO2max', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test demi-Cooper', 'Course 6 minutes pour VMA', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test VAMEVAL', 'Test VMA sur piste', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test 1RM', 'Test de répétition maximale', 'avancé', NULL),
  ('Tests & Évaluations', 'Test 3RM', 'Test 3 répétitions maximales', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test 5RM', 'Test 5 répétitions maximales', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test FMS', 'Functional Movement Screen', 'débutant', NULL),
  ('Tests & Évaluations', 'Test Beep', 'Test navette intermittent', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test Yo-Yo IR1', 'Test intermittent niveau 1', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test Yo-Yo IR2', 'Test intermittent niveau 2', 'avancé', NULL),
  ('Tests & Évaluations', 'CMJ (Counter Movement Jump)', 'Saut avec contre-mouvement', 'débutant', NULL),
  ('Tests & Évaluations', 'SJ (Squat Jump)', 'Saut depuis position statique', 'débutant', NULL),
  ('Tests & Évaluations', 'Drop Jump Test', 'Test de réactivité en saut', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test détente horizontale', 'Saut en longueur sans élan', 'débutant', NULL),
  ('Tests & Évaluations', 'Sprint 10m', 'Test de vitesse courte', 'débutant', NULL),
  ('Tests & Évaluations', 'Sprint 20m', 'Test de vitesse', 'débutant', NULL),
  ('Tests & Évaluations', 'Sprint 40m', 'Test de vitesse maximale', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test Illinois', 'Test d''agilité', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test T', 'Test d''agilité en T', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test Sit & Reach', 'Test de souplesse ischio-jambiers', 'débutant', NULL),
  ('Tests & Évaluations', 'Test Thomas', 'Test de souplesse psoas', 'débutant', NULL),
  ('Tests & Évaluations', 'Test planche (max)', 'Temps maximal en planche', 'débutant', NULL),
  ('Tests & Évaluations', 'Test pompes max', 'Nombre max de pompes', 'débutant', NULL),
  ('Tests & Évaluations', 'Test tractions max', 'Nombre max de tractions', 'intermédiaire', NULL),
  ('Tests & Évaluations', 'Test Wingate', 'Test puissance anaérobie vélo', 'avancé', NULL),
  ('Tests & Évaluations', 'Test Ruffier-Dickson', 'Test de récupération cardiaque', 'débutant', NULL),
  ('Tests & Évaluations', 'Pesée / Impédancemétrie', 'Mesure composition corporelle', 'débutant', NULL),
  ('Tests & Évaluations', 'Test mobilité épaule', 'Évaluation amplitude épaule', 'débutant', NULL),
  ('Tests & Évaluations', 'Test mobilité hanche', 'Évaluation amplitude hanche', 'débutant', NULL)
)
INSERT INTO public.exercise_library (
  name, station_name, category, description, tips, difficulty, is_system, user_id
)
SELECT
  src.name,
  src.station_name,
  CASE src.station_name
    WHEN 'Cardio/Endurance' THEN 'running_ef'
    WHEN 'Vitesse/Plyométrie' THEN 'plyometrics'
    WHEN 'Haltérophilie' THEN 'halterophilie_complexes'
    WHEN 'Gainage/Core' THEN 'core'
    WHEN 'Poids de corps/Calisthenics' THEN 'bodyweight_full'
    WHEN 'Athlétisme/Running drills' THEN 'running_ef'
    WHEN 'Prévention/Renforcement' THEN 'reathletisation_lower'
    WHEN 'Respiration' THEN 'breathing'
    WHEN 'Réathlétisation' THEN 'reathletisation_lower'
    WHEN 'Tests & Évaluations' THEN 'musculation'
    ELSE 'hyrox_stations'
  END AS category,
  src.description,
  src.tips,
  CASE src.difficulty
    WHEN 'débutant' THEN 'beginner'
    WHEN 'intermédiaire' THEN 'intermediate'
    WHEN 'avancé' THEN 'advanced'
    ELSE 'intermediate'
  END AS difficulty,
  true AS is_system,
  NULL::uuid AS user_id
FROM src
WHERE NOT EXISTS (
  SELECT 1 FROM public.exercise_library el
  WHERE el.is_system = true
    AND lower(el.name) = lower(src.name)
    AND lower(coalesce(el.station_name, '')) = lower(src.station_name)
);